#!/bin/bash

# Color
N="\e[0m"
BD="\e[1m"
DM="\e[2m"
IT="\e[3m"
UL="\e[4m"
#BG="\e[1;7m"
BG="\e[1;7;38;5;228m"
HD="\e[8m"
ST="\e[9m"
BK="\e[30m"
RD="\e[31m"
GN="\e[32m"
YL="\e[33m"
BL="\e[34m"
MG="\e[35m"
CY="\e[36m"
#GR="\e[90m"
GR="\e[1;38;5;166m"
LRD="\e[91m"
#LGN="\e[92m"
LGN="\e[1;38;5;046m"
#LYL="\e[93m"
LYL="\e[1;38;5;227m"
LBL="\e[94m"
LMG="\e[95m"
LCY="\e[96m"
LWH="\e[97m"
RDB="\e[1;7;91m"
GNB="\e[1;7;92m"
YLB="\e[1;7;93m"
BLB="\e[1;7;94m"
MGB="\e[1;7;95m"
CYB="\e[1;7;96m"
GRB="\e[1;7;97m"
RDBW="\e[41;30m"
GNBW="\e[42;30m"
YLBW="\e[43;30m"
BLBW="\e[44;30m"
MGBW="\e[45;30m"
CYBW="\e[46;30m"
GRBW="\e[47;30m"
C1="\e[1;38;5;166m"

width=$(tput cols)
if [[ $width -lt 66 ]]; then
	let x=53 y=$width-x z=y/2
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "${LYL}████████${N}${GR}╗${LYL}███████${N}${GR}╗${LYL}██████${N}${GR}╗ ${LYL}███${N}${GR}╗   ${LYL}███${N}${GR}╗${LYL}██${N}${GR}╗   ${LYL}██${N}${GR}╗${LYL}██${N}${GR}╗  ${LYL}██${N}${GR}╗${N}"
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "${GR}╚══${LYL}██${N}${GR}╔══╝${LYL}██${N}${GR}╔════╝${LYL}██${N}${GR}╔══${LYL}██${N}${GR}╗${LYL}████${N}${GR}╗ ${LYL}████${N}${GR}║${LYL}██${N}${GR}║   ${LYL}██${N}${GR}║╚${LYL}██${N}${GR}╗${LYL}██${N}${GR}╔╝${N}"
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "   ${LYL}██${N}${GR}║   ${LYL}█████${N}${GR}╗  ${LYL}██████${N}${GR}╔╝${LYL}██${N}${GR}╔${LYL}████${N}${GR}╔${LYL}██${N}${GR}║${LYL}██${N}${GR}║   ${LYL}██${N}${GR}║ ╚${LYL}███${N}${GR}╔╝${N}"
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "   ${LYL}██${N}${GR}║   ${LYL}██${N}${GR}╔══╝  ${LYL}██${N}${GR}╔══${LYL}██${N}${GR}╗${LYL}██${N}${GR}║╚${LYL}██${N}${GR}╔╝${LYL}██${N}${GR}║${LYL}██${N}${GR}║   ${LYL}██${N}${GR}║ ${LYL}██${N}${GR}╔${LYL}██${N}${GR}╗${N}"
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "   ${LYL}██${N}${GR}║   ${LYL}███████${N}${GR}╗${LYL}██${N}${GR}║  ${LYL}██${N}${GR}║${LYL}██${N}${GR}║ ╚═╝ ${LYL}██${N}${GR}║╚${LYL}██████${N}${GR}╔╝${LYL}██${N}${GR}╔╝╚${LYL}██${N}${GR}╗${N}"
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "   ${GR}╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝${N}"
	echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "${BG}❘ ANDROID TERMINAL EMULATOR / GNU LINUX ENVIRONMENT ❘${N}"
	echo ""
else
  let x=64 y=$width-x z=y/2
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "█▀▀▀▀▀▀▀▀█ ${LYL}████████${N}${GR}╗${LYL}███████${N}${GR}╗${LYL}██████${N}${GR}╗ ${LYL}███${N}${GR}╗   ${LYL}███${N}${GR}╗${LYL}██${N}${GR}╗   ${LYL}██${N}${GR}╗${LYL}██${N}${GR}╗  ${LYL}██${N}${GR}╗${N}"
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "█ ${LGN}▀▄   ${N}  █ ${GR}╚══${LYL}██${N}${GR}╔══╝${LYL}██${N}${GR}╔════╝${LYL}██${N}${GR}╔══${LYL}██${N}${GR}╗${LYL}████${N}${GR}╗ ${LYL}████${N}${GR}║${LYL}██${N}${GR}║   ${LYL}██${N}${GR}║╚${LYL}██${N}${GR}╗${LYL}██${N}${GR}╔╝${N}"
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "█ ${LGN}▄▀ ▄▄${N}  █    ${LYL}██${N}${GR}║   ${LYL}█████${N}${GR}╗  ${LYL}██████${N}${GR}╔╝${LYL}██${N}${GR}╔${LYL}████${N}${GR}╔${LYL}██${N}${GR}║${LYL}██${N}${GR}║   ${LYL}██${N}${GR}║ ╚${LYL}███${N}${GR}╔╝${N}"
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "█▄▄▄▄▄▄▄▄█    ${LYL}██${N}${GR}║   ${LYL}██${N}${GR}╔══╝  ${LYL}██${N}${GR}╔══${LYL}██${N}${GR}╗${LYL}██${N}${GR}║╚${LYL}██${N}${GR}╔╝${LYL}██${N}${GR}║${LYL}██${N}${GR}║   ${LYL}██${N}${GR}║ ${LYL}██${N}${GR}╔${LYL}██${N}${GR}╗${N}"
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "   ▀▀▀▀       ${LYL}██${N}${GR}║   ${LYL}███████${N}${GR}╗${LYL}██${N}${GR}║  ${LYL}██${N}${GR}║${LYL}██${N}${GR}║ ╚═╝ ${LYL}██${N}${GR}║╚${LYL}██████${N}${GR}╔╝${LYL}██${N}${GR}╔╝╚${LYL}██${N}${GR}╗${N}"
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "▀▀▀▀▀▀▀▀▀▀    ${GR}╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝${N}"
  echo "" | awk '{ printf "%-'$z's", $0 }' && echo -e "${BG}❘ ANDROID TERMINAL EMULATOR POWERED BY LINUX BASED ENVIRONMENT ❘${N}"
  echo ""
fi
